import { defineNuxtConfig } from "nuxt/config";
import highlights from "./config/highlights";

export default defineNuxtConfig({
  compatibilityDate: "2025-11-06",
  imports: {
    dirs: ["types", "recipes"],
  },
  modules: ["@pinia/nuxt", "reka-ui/nuxt", "@unocss/nuxt", "@nuxt/content"],
  content: {
    build: {
      markdown: {
        highlight: {
          theme: {
            default: highlights,
          },
        },
      },
    },
  },
  iconic: {
    // Theme
    light: "ic:twotone-light-mode",
    dark: "ic:twotone-dark-mode",
    theme: "ic:twotone-palette",

    // Translate
    translate: "ic:twotone-translate",

    // Navigation
    home: "ic:twotone-home",
    menu: "ic:twotone-menu",
    close: "ic:twotone-close",
    search: "ic:twotone-search",

    // Actions
    add: "ic:twotone-add",
    edit: "ic:twotone-edit",
    delete: "ic:twotone-delete",
    save: "ic:twotone-save",

    // Arrows
    "arrow-up": "ic:twotone-arrow-upward",
    "arrow-down": "ic:twotone-arrow-downward",
    "arrow-left": "ic:twotone-arrow-back",
    "arrow-right": "ic:twotone-arrow-forward",

    // Chevrons
    "chevron-up": "ic:twotone-keyboard-arrow-up",
    "chevron-down": "ic:twotone-keyboard-arrow-down",
    "chevron-left": "ic:twotone-keyboard-arrow-left",
    "chevron-right": "ic:twotone-keyboard-arrow-right",

    // UI
    settings: "ic:twotone-settings",
    user: "ic:twotone-person",
    check: "ic:twotone-check",
    info: "ic:twotone-info",
    warning: "ic:twotone-warning",
    error: "ic:twotone-error",

    // Sample flags
    "flag-us": "circle-flags:us",
    "flag-gb": "circle-flags:gb",
    "flag-fr": "circle-flags:fr",
    "flag-mx": "circle-flags:mx",
  },
  untheme: {
    roles: {
      a: {
        text: "sys-primary",
        "text-hover": "sys-primary-hover",
        "text-active": "sys-primary-active",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-normal",
        "line-height": "ref-leading-normal",
        "text-decoration": "ref-decoration-none",
        cursor: "ref-cursor-pointer",
      },
      button: {
        cursor: "ref-cursor-pointer",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        "outline-color": "sys-focus",
        "outline-width": "ref-outline-width-medium",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
      },
      "accordion-trigger": {
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "text-align": "ref-align-start",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-xs",
        width: "ref-full",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-sm",
        "padding-bottom": "ref-spacing-sm",
        "font-weight-selected": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-selected-hover": "ref-font-bold",
        "font-weight-selected-active": "ref-font-bold",
        "font-weight-selected-focus": "ref-font-bold",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-focus-inset",
      },
      "accordion-content": {
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
      },
      aside: {
        background: "sys-surface",
        text: "sys-on-surface",
        "border-color": "ref-color-transparent",
        "border-right-width": "ref-border-width-thin",
        "border-right-color": "sys-outline-variant",
        "border-right-style": "ref-border-style-solid",
        "grid-row": "ref-grid-row-2",
        "grid-column": "ref-grid-col-1",
        width: "ref-width-sm",
        height: "ref-height-full",
        "box-shadow": "ref-shadow-sm",
      },
      header: {
        background: "sys-surface",
        text: "sys-on-surface",
        gap: "ref-spacing-md",
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-trifold",
        "grid-column": "ref-grid-col-span-all",
        "align-items": "ref-align-center",
        "border-bottom-style": "ref-border-style-solid",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-color": "sys-outline-variant",
      },
      icon: {
        text: "ref-color-current",
        opacity: "ref-opacity-100",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        width: "ref-width-1em",
        height: "ref-height-1em",
      },
      "listbox-root": {
        background: "ref-color-transparent",
      },
      "listbox-content": {
        background: "ref-color-transparent",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-none",
      },
      "listbox-item": {
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "background-selected": "sys-hover",
        "background-selected-hover": "sys-hover",
        "box-shadow-selected": "ref-shadow-border-left",
        "box-shadow-selected-hover": "ref-shadow-border-left",
        "box-shadow-selected-active": "ref-shadow-border-left",
        "border-color": "ref-color-transparent",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        cursor: "ref-cursor-pointer",
        "cursor-disabled": "ref-cursor-not-allowed",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-selected": "ref-font-bold",
        "font-weight-selected-hover": "ref-font-bold",
        "font-weight-selected-active": "ref-font-bold",
        "font-weight-selected-focus": "ref-font-bold",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-sm",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-left-focus",
      },
      "tabs-root": {
        background: "ref-color-transparent",
      },
      "tabs-list": {
        background: "ref-color-transparent",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        gap: "ref-spacing-none",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-color": "sys-outline-variant",
        "border-bottom-style": "ref-border-style-solid",
      },
      "tabs-trigger": {
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        "box-shadow-selected": "ref-shadow-border-bottom",
        "box-shadow-selected-hover": "ref-shadow-border-bottom",
        "box-shadow-selected-active": "ref-shadow-border-bottom",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-selected": "ref-font-bold",
        "font-weight-selected-hover": "ref-font-bold",
        "font-weight-selected-active": "ref-font-bold",
        "font-weight-selected-focus": "ref-font-bold",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-bottom-focus",
      },
      "tabs-content": {
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
      },
      main: {
        background: "sys-surface",
        text: "sys-on-surface",
        height: "ref-viewport-height",
        "min-height": "ref-viewport-height",
        "max-height": "ref-viewport-height",
        display: "ref-display-grid",
        "grid-template-rows": "ref-layout-nav-content",
        "grid-template-columns": "ref-layout-sidebar-left",
      },
      section: {
        background: "ref-color-transparent",
        text: "sys-on-surface",
      },
      article: {
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "max-width": "ref-width-prose",
        "line-height": "ref-leading-relaxed",
        display: "ref-display-block",
        "padding-top": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-lg",
        "padding-left": "ref-spacing-lg",
      },
      nav: {
        background: "ref-color-transparent",
        text: "sys-on-surface",
      },
      footer: {
        background: "sys-surface",
        text: "sys-on-surface",
        gap: "ref-spacing-md",
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-trifold",
        "grid-column": "ref-grid-col-span-all",
        "align-items": "ref-align-center",
        "border-top-style": "ref-border-style-solid",
        "border-top-width": "ref-border-width-thin",
        "border-top-color": "sys-outline-variant",
      },
      p: {
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-normal",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
      },
      h1: {
        text: "sys-on-surface",
        "font-size": "ref-text-4xl",
        "font-weight": "ref-font-bold",
        "line-height": "ref-leading-tighter",
        display: "ref-display-block",
        "margin-top": "ref-spacing-none",
        "margin-bottom": "ref-spacing-xl",
      },
      h2: {
        text: "sys-on-surface",
        "font-size": "ref-text-2xl",
        "font-weight": "ref-font-bold",
        "line-height": "ref-leading-snug",
        display: "ref-display-block",
        "margin-top": "ref-spacing-2xl",
        "margin-bottom": "ref-spacing-lg",
      },
      h3: {
        text: "sys-on-surface",
        "font-size": "ref-text-xl",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-cozy",
        display: "ref-display-block",
        "margin-top": "ref-spacing-xl",
        "margin-bottom": "ref-spacing-sm",
      },
      h4: {
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
      },
      h5: {
        text: "sys-on-surface-variant",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
      },
      h6: {
        text: "sys-on-surface-variant",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-medium",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
      },
      code: {
        text: "sys-on-surface",
        background: "sys-hover",
        "font-family": "ref-font-mono",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-2xs",
        "padding-right": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-2xs",
        "padding-left": "ref-spacing-xs",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-color": "sys-outline-variant",
        "border-right-color": "sys-outline-variant",
        "border-bottom-color": "sys-outline-variant",
        "border-left-color": "sys-outline-variant",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        display: "ref-display-inline-block",
      },
      pre: {
        text: "sys-on-surface",
        background: "sys-hover",
        "font-family": "ref-font-mono",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        "padding-left": "ref-spacing-md",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-color": "sys-outline-variant",
        "border-right-color": "sys-outline-variant",
        "border-bottom-color": "sys-outline-variant",
        "border-left-color": "sys-outline-variant",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        display: "ref-display-block",
        "overflow-x": "ref-overflow-auto",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
      },
      strong: {
        "font-weight": "ref-font-bold",
        display: "ref-display-inline",
      },
      em: {
        "font-style": "ref-font-italic",
        display: "ref-display-inline",
      },
      blockquote: {
        text: "sys-on-surface-variant",
        "font-style": "ref-font-italic",
        "border-left-width": "ref-border-width-thick",
        "border-left-color": "sys-outline-variant",
        "border-left-style": "ref-border-style-solid",
        "padding-left": "ref-spacing-lg",
        "margin-top": "ref-spacing-xl",
        "margin-bottom": "ref-spacing-xl",
        display: "ref-display-block",
      },
      hr: {
        "border-top-width": "ref-border-width-thin",
        "border-top-color": "sys-outline-variant",
        "border-top-style": "ref-border-style-solid",
        "margin-top": "ref-spacing-2xl",
        "margin-bottom": "ref-spacing-2xl",
        display: "ref-display-block",
      },
      ul: {
        "list-style-type": "ref-list-disc",
        "padding-left": "ref-spacing-xl",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
        display: "ref-display-block",
      },
      ol: {
        "list-style-type": "ref-list-decimal",
        "padding-left": "ref-spacing-xl",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
        display: "ref-display-block",
      },
      li: {
        display: "ref-display-list-item",
        "margin-top": "ref-spacing-xs",
        "margin-bottom": "ref-spacing-xs",
      },
    },
  },
  vite: {
    optimizeDeps: {
      exclude: ["#build/untheme.config.mjs", "#build/iconic.config.mjs"],
    },
  },
});
