import { defineNuxtPlugin } from "#app";
import type { LogLevel, LogEntry, HookEntry } from "../src/types";
import { meetsLevel } from "../src/levels";
import { isLogEntry, isLogLevel, hookEntryLevel, hookEntryFields } from "../src/guards";
import { extractData, sanitizeData } from "../src/sanitize";

// @ts-ignore — virtual module generated by the crucible Nuxt module
import crucibleConfig from "#build/crucible.config.mjs";

const batching = crucibleConfig.batch as boolean;
const queue: LogEntry[] = [];
let flushTimer: ReturnType<typeof setTimeout> | null = null;

const send = (entries: LogEntry[]): void => {
  const body = JSON.stringify(entries);
  if (navigator.sendBeacon("/api/crucible", body)) return;
  fetch("/api/crucible", {
    method: "POST",
    body,
    headers: { "Content-Type": "application/json" },
    keepalive: true,
  }).catch(() => {});
};

const flush = (): void => {
  if (queue.length === 0) return;
  send(queue.splice(0, queue.length));
};

const scheduleFlush = (): void => {
  if (flushTimer) return;
  flushTimer = setTimeout(() => {
    flushTimer = null;
    flush();
  }, 5000);
};

const transmit = (entry: LogEntry): void => {
  if (batching) {
    queue.push(entry);
    scheduleFlush();
  } else {
    send([entry]);
  }
};

export default defineNuxtPlugin({
  name: "crucible:client",
  setup(nuxtApp) {
    const hookMap = crucibleConfig.hookLevels as Record<string, HookEntry>;
    const minimum = isLogLevel(crucibleConfig.minLevel) ? crucibleConfig.minLevel : "debug";

    window.addEventListener("beforeunload", flush);

    nuxtApp.hooks.afterEach((event) => {
      const name = String(event.name);

      let entry: LogEntry;

      if (name.startsWith("log:") && isLogEntry(event.args[0])) {
        entry = { ...event.args[0], data: sanitizeData(event.args[0].data), source: "client" };
      } else {
        const mapped = hookMap[name] || "debug";
        const level: LogLevel = hookEntryLevel(mapped);
        if (!meetsLevel(level, minimum)) return;

        const fields = hookEntryFields(mapped);
        const data = extractData(event.args[0], fields);

        entry = {
          level,
          message: name,
          timestamp: Date.now(),
          hook: name,
          source: "client",
          ...(data ? { data } : {}),
        };
      }

      if (!meetsLevel(entry.level, minimum)) return;

      transmit(entry);
    });
  },
});
