import { defineNuxtPlugin } from "#app";
import type { TelemetryEntry, LogEntry, SpanEntry } from "../src/types";
import { meetsLevel } from "../src/levels";
import { isLogLevel } from "../src/guards";
import { sanitizeData } from "../src/sanitize";
import { generateTraceId, generateSpanId, formatTraceparent } from "../src/trace-id";
import { getTraceContext, setTraceContext } from "./trace-context";
import { initMetrics } from "./metrics";

// @ts-ignore — virtual module generated by the crucible Nuxt module
import crucibleConfig from "#build/crucible.config.mjs";

const batching = crucibleConfig.batch as boolean;
const minimum = isLogLevel(crucibleConfig.minLevel) ? crucibleConfig.minLevel : "debug";
const tracesConfig = crucibleConfig.traces as boolean | Record<string, boolean> | undefined;
const tracesEnabled = tracesConfig !== false;
const fetchTracing = tracesEnabled && (tracesConfig === true || typeof tracesConfig !== "object" || tracesConfig?.fetch !== false);
const navigationTracing = tracesEnabled && (tracesConfig === true || typeof tracesConfig !== "object" || tracesConfig?.navigation !== false);

const metricsConfig = crucibleConfig.metrics as boolean | Record<string, boolean> | undefined;
const metricsEnabled = metricsConfig !== false;

const queue: TelemetryEntry[] = [];
let flushTimer: ReturnType<typeof setTimeout> | null = null;

const send = (entries: TelemetryEntry[]): void => {
  const body = JSON.stringify(entries);
  if (navigator.sendBeacon("/api/crucible", body)) return;
  fetch("/api/crucible", {
    method: "POST",
    body,
    headers: { "Content-Type": "application/json" },
    keepalive: true,
  }).catch(() => {});
};

const flush = (): void => {
  if (queue.length === 0) return;
  send(queue.splice(0, queue.length));
};

const scheduleFlush = (): void => {
  if (flushTimer) return;
  flushTimer = setTimeout(() => {
    flushTimer = null;
    flush();
  }, 5000);
};

const transmit = (entry: TelemetryEntry): void => {
  if ((!entry.kind || entry.kind === "log") && !meetsLevel((entry as LogEntry).level, minimum)) return;

  let sanitized: TelemetryEntry;
  if (!entry.kind || entry.kind === "log") {
    sanitized = { ...entry, data: sanitizeData((entry as LogEntry).data), source: "client" } as LogEntry;
  } else {
    sanitized = { ...entry, source: "client" };
  }

  if (batching) {
    queue.push(sanitized);
    scheduleFlush();
  } else {
    send([sanitized]);
  }
};

export default defineNuxtPlugin({
  name: "crucible:client",
  setup(nuxtApp) {
    window.addEventListener("beforeunload", flush);

    // --- Navigation tracing ---
    if (navigationTracing) {
      let navSpan: SpanEntry | null = null;

      nuxtApp.hook("page:start", () => {
        const traceId = generateTraceId();
        const spanId = generateSpanId();
        setTraceContext({ traceId, rootSpanId: spanId, activeSpanId: spanId });
        navSpan = {
          kind: "span",
          traceId,
          spanId,
          name: "navigation",
          startTime: Date.now(),
          status: "unset",
        };
      });

      nuxtApp.hook("page:finish", () => {
        if (navSpan) {
          navSpan.endTime = Date.now();
          navSpan.status = "ok";
          transmit(navSpan);
          navSpan = null;
        }
        setTraceContext(null);
      });
    }

    // --- fetch tracing ---
    if (fetchTracing) {
      const originalFetch = globalThis.fetch;
      globalThis.fetch = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
        const ctx = getTraceContext();
        if (!ctx) return originalFetch(input, init);

        const childSpanId = generateSpanId();
        const traceparent = formatTraceparent(ctx.traceId, childSpanId);
        const headers = new Headers(init?.headers);
        headers.set("traceparent", traceparent);

        let name: string;
        if (typeof input === "string") name = input;
        else if (input instanceof URL) name = input.pathname;
        else name = input.url;

        // Don't trace our own telemetry submissions
        if (name.includes("/api/crucible")) return originalFetch(input, init);

        const startTime = Date.now();

        return originalFetch(input, { ...init, headers })
          .then((response) => {
            transmit({
              kind: "span",
              traceId: ctx.traceId,
              spanId: childSpanId,
              parentSpanId: ctx.activeSpanId,
              name: `fetch ${name}`,
              startTime,
              endTime: Date.now(),
              status: response.ok ? "ok" : "error",
              attributes: {
                "http.status_code": response.status,
                "http.url": name,
              },
            });
            return response;
          })
          .catch((error) => {
            transmit({
              kind: "span",
              traceId: ctx.traceId,
              spanId: childSpanId,
              parentSpanId: ctx.activeSpanId,
              name: `fetch ${name}`,
              startTime,
              endTime: Date.now(),
              status: "error",
              attributes: { error: String(error), "http.url": name },
            });
            throw error;
          });
      };
    }

    // --- Metrics collection ---
    if (metricsEnabled) {
      const opts = typeof metricsConfig === "object" ? metricsConfig : {};
      initMetrics(transmit, {
        webVitals: opts.webVitals !== false,
        resources: opts.resources === true,
        longTasks: opts.longTasks !== false,
        connection: opts.connection !== false,
      });
    }

    return { provide: { transmit } };
  },
});
